ALLELE_CATALOG: list[dict[str, str | bool | None]] = [
    # EYES
    {
        "id": "round_eyes",
        "trait_category": "EYES",
        "name": "Round eyes",
        "is_dominant": False,
        "sprite_key": "eyes/round_eyes",
    },
    {
        "id": "heart_eyes",
        "trait_category": "EYES",
        "name": "Heart eyes",
        "is_dominant": False,
        "sprite_key": "eyes/heart_eyes",
    },
    {
        "id": "almond_eyes",
        "trait_category": "EYES",
        "name": "Almond eyes",
        "is_dominant": True,
        "sprite_key": "eyes/almond_eyes",
    },
    {
        "id": "big_eyes",
        "trait_category": "EYES",
        "name": "Big eyes",
        "is_dominant": True,
        "sprite_key": "eyes/big_eyes",
    },
    # SKULL_TOP
    {
        "id": "no_horn",
        "trait_category": "SKULL_TOP",
        "name": "No horn",
        "is_dominant": False,
        "sprite_key": "skull_top/no_horn",
    },
    {
        "id": "heart_horn",
        "trait_category": "SKULL_TOP",
        "name": "Heart horn",
        "is_dominant": False,
        "sprite_key": "skull_top/heart_horn",
    },
    {
        "id": "small_horn",
        "trait_category": "SKULL_TOP",
        "name": "Small horn",
        "is_dominant": True,
        "sprite_key": "skull_top/small_horn",
    },
    {
        "id": "small_crest",
        "trait_category": "SKULL_TOP",
        "name": "Small crest",
        "is_dominant": True,
        "sprite_key": "skull_top/small_crest",
    },
    # DORSAL
    {
        "id": "no_dorsal",
        "trait_category": "DORSAL",
        "name": "No dorsal",
        "is_dominant": False,
        "sprite_key": "dorsal/no_dorsal",
    },
    {
        "id": "heart_dorsal",
        "trait_category": "DORSAL",
        "name": "Heart dorsal",
        "is_dominant": False,
        "sprite_key": "dorsal/heart_dorsal",
    },
    {
        "id": "small_wings",
        "trait_category": "DORSAL",
        "name": "Small wings",
        "is_dominant": True,
        "sprite_key": "dorsal/small_wings",
    },
    {
        "id": "small_spikes",
        "trait_category": "DORSAL",
        "name": "Small spikes",
        "is_dominant": True,
        "sprite_key": "dorsal/small_spikes",
    },
    # CAUDAL
    {
        "id": "no_tail",
        "trait_category": "CAUDAL",
        "name": "No tail",
        "is_dominant": False,
        "sprite_key": "caudal/no_tail",
    },
    {
        "id": "heart_tail",
        "trait_category": "CAUDAL",
        "name": "Heart tail",
        "is_dominant": False,
        "sprite_key": "caudal/heart_tail",
    },
    {
        "id": "short_tail",
        "trait_category": "CAUDAL",
        "name": "Short tail",
        "is_dominant": True,
        "sprite_key": "caudal/short_tail",
    },
    {
        "id": "short_fin_tail",
        "trait_category": "CAUDAL",
        "name": "Short fin tail",
        "is_dominant": True,
        "sprite_key": "caudal/short_fin_tail",
    },
    # COLOR
    {
        "id": "light_grey",
        "trait_category": "COLOR",
        "name": "Light grey",
        "is_dominant": False,
        "sprite_key": "color/light_grey",
    },
    {
        "id": "pink",
        "trait_category": "COLOR",
        "name": "Pink",
        "is_dominant": False,
        "sprite_key": "color/pink",
    },
    {
        "id": "light_blue",
        "trait_category": "COLOR",
        "name": "Light blue",
        "is_dominant": True,
        "sprite_key": "color/light_blue",
    },
    {
        "id": "light_green",
        "trait_category": "COLOR",
        "name": "Light green",
        "is_dominant": True,
        "sprite_key": "color/light_green",
    },
    {
        "id": "light_red",
        "trait_category": "COLOR",
        "name": "Light red",
        "is_dominant": True,
        "sprite_key": "color/light_red",
    },
]
