"""add biome_id to allele

Revision ID: 0c3c01712ce0
Revises: 72bd9ba67918
Create Date: 2026-06-30 09:34:35.893139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3c01712ce0'
down_revision: Union[str, Sequence[str], None] = '72bd9ba67918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alleles', sa.Column('biome_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(op.f('fk_alleles_biome_id_biomes'), 'alleles', 'biomes', ['biome_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_alleles_biome_id_biomes'), 'alleles', type_='foreignkey')
    op.drop_column('alleles', 'biome_id')
    # ### end Alembic commands ###
