"""add daily cycle and training fields to creature

Revision ID: 251a8f9f81c3
Revises: d7278486924a
Create Date: 2026-07-03 15:01:41.853748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251a8f9f81c3'
down_revision: Union[str, Sequence[str], None] = 'd7278486924a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creatures', sa.Column('is_asleep', sa.Boolean(), nullable=False))
    op.add_column('creatures', sa.Column('woke_up_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('creatures', sa.Column('went_to_sleep_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('creatures', sa.Column('trainings_done_today', sa.Integer(), nullable=False))
    op.add_column('creatures', sa.Column('last_trained_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('creatures', sa.Column('pending_training_force', sa.Float(), nullable=False))
    op.add_column('creatures', sa.Column('pending_training_beauty', sa.Float(), nullable=False))
    op.add_column('creatures', sa.Column('pending_training_size', sa.Float(), nullable=False))
    op.add_column('creatures', sa.Column('mentor_id', sa.Uuid(), nullable=True))
    op.add_column('creatures', sa.Column('mentor_since', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_creatures_mentor_id_creatures'), 'creatures', 'creatures', ['mentor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_creatures_mentor_id_creatures'), 'creatures', type_='foreignkey')
    op.drop_column('creatures', 'mentor_since')
    op.drop_column('creatures', 'mentor_id')
    op.drop_column('creatures', 'pending_training_size')
    op.drop_column('creatures', 'pending_training_beauty')
    op.drop_column('creatures', 'pending_training_force')
    op.drop_column('creatures', 'last_trained_at')
    op.drop_column('creatures', 'trainings_done_today')
    op.drop_column('creatures', 'went_to_sleep_at')
    op.drop_column('creatures', 'woke_up_at')
    op.drop_column('creatures', 'is_asleep')
    # ### end Alembic commands ###
