"""initial schema

Revision ID: d13a132e689f
Revises:
Create Date: 2026-06-28 18:23:41.060718

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d13a132e689f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alleles",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column(
            "trait_category",
            sa.Enum("EYES", "SKULL_TOP", "DORSAL", "CAUDAL", "COLOR", name="traitcategory"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_dominant", sa.Boolean(), nullable=False),
        sa.Column("sprite_key", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alleles")),
    )
    op.create_table(
        "biomes",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unlocked_by_default", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_biomes")),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("currency", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "creatures",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "life_stage",
            sa.Enum("BABY", "CHILD", "ADOLESCENT", "YOUNG_ADULT", "ADULT", name="lifestage"),
            nullable=False,
        ),
        sa.Column(
            "stage_started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("biome_id", sa.String(length=50), nullable=True),
        sa.Column("parent1_id", sa.Uuid(), nullable=True),
        sa.Column("parent2_id", sa.Uuid(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_alive", sa.Boolean(), nullable=False),
        sa.Column(
            "death_cause",
            sa.Enum("STARVATION", "DISEASE", "ESCAPE", name="deathcause"),
            nullable=True,
        ),
        sa.Column(
            "max_stage_reached",
            sa.Enum("BABY", "CHILD", "ADOLESCENT", "YOUNG_ADULT", "ADULT", name="lifestage"),
            nullable=False,
        ),
        sa.Column("autonomy", sa.Float(), nullable=False),
        sa.Column("hunger", sa.Float(), nullable=False),
        sa.Column("health", sa.Float(), nullable=False),
        sa.Column("happiness", sa.Float(), nullable=False),
        sa.Column("training_force", sa.Float(), nullable=False),
        sa.Column("training_beauty", sa.Float(), nullable=False),
        sa.Column("training_size", sa.Float(), nullable=False),
        sa.Column("reproduction_count", sa.Integer(), nullable=False),
        sa.Column(
            "last_interaction_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("time_frozen", sa.Boolean(), nullable=False),
        sa.Column("freeze_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["biome_id"], ["biomes.id"], name=op.f("fk_creatures_biome_id_biomes")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_creatures_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["parent1_id"], ["creatures.id"], name=op.f("fk_creatures_parent1_id_creatures")
        ),
        sa.ForeignKeyConstraint(
            ["parent2_id"], ["creatures.id"], name=op.f("fk_creatures_parent2_id_creatures")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creatures")),
    )
    op.create_index(op.f("ix_creatures_owner_id"), "creatures", ["owner_id"], unique=False)
    op.create_table(
        "wild_gene_pool",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("allele_id", sa.String(length=100), nullable=False),
        sa.Column(
            "unlocked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["allele_id"], ["alleles.id"], name=op.f("fk_wild_gene_pool_allele_id_alleles")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_wild_gene_pool_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", "allele_id", "id", name=op.f("pk_wild_gene_pool")),
    )
    op.create_table(
        "creature_genomes",
        sa.Column("creature_id", sa.Uuid(), nullable=False),
        sa.Column(
            "trait_category",
            sa.Enum("EYES", "SKULL_TOP", "DORSAL", "CAUDAL", "COLOR", name="traitcategory"),
            nullable=False,
        ),
        sa.Column("allele_from_parent1", sa.String(length=100), nullable=False),
        sa.Column("allele_from_parent2", sa.String(length=100), nullable=False),
        sa.Column("expressed_allele", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["allele_from_parent1"],
            ["alleles.id"],
            name=op.f("fk_creature_genomes_allele_from_parent1_alleles"),
        ),
        sa.ForeignKeyConstraint(
            ["allele_from_parent2"],
            ["alleles.id"],
            name=op.f("fk_creature_genomes_allele_from_parent2_alleles"),
        ),
        sa.ForeignKeyConstraint(
            ["creature_id"],
            ["creatures.id"],
            name=op.f("fk_creature_genomes_creature_id_creatures"),
        ),
        sa.ForeignKeyConstraint(
            ["expressed_allele"],
            ["alleles.id"],
            name=op.f("fk_creature_genomes_expressed_allele_alleles"),
        ),
        sa.PrimaryKeyConstraint(
            "creature_id", "trait_category", "id", name=op.f("pk_creature_genomes")
        ),
    )
    op.create_table(
        "interaction_logs",
        sa.Column("creature_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type", sa.Enum("FEED", "PLAY", "HEAL", "TRAIN", name="interactiontype"), nullable=False
        ),
        sa.Column(
            "train_target", sa.Enum("FORCE", "BEAUTY", "SIZE", name="traintarget"), nullable=True
        ),
        sa.Column("mentor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "performed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creature_id"],
            ["creatures.id"],
            name=op.f("fk_interaction_logs_creature_id_creatures"),
        ),
        sa.ForeignKeyConstraint(
            ["mentor_id"], ["creatures.id"], name=op.f("fk_interaction_logs_mentor_id_creatures")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction_logs")),
    )
    op.create_index(
        op.f("ix_interaction_logs_creature_id"), "interaction_logs", ["creature_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interaction_logs_creature_id"), table_name="interaction_logs")
    op.drop_table("interaction_logs")
    op.drop_table("creature_genomes")
    op.drop_table("wild_gene_pool")
    op.drop_index(op.f("ix_creatures_owner_id"), table_name="creatures")
    op.drop_table("creatures")
    op.drop_table("users")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("biomes")
    op.drop_table("alleles")
    # ### end Alembic commands ###
